### ISSUE TITLE
Maya rig mental ray issue

### ISSUE THREAD

**Issue by Endertainer** [Ravbug/ravbug.github.io#1]
So I got this issue when opening a Maya rig on my installation of Maya 2020. I got a shader engine error in about NVIDIA Mental Ray nodes, while I don't know how to install it. Is there any way I can fix this issue?

**Comment by Ravbug** [comment]
You can safely ignore the warning message. The rig should work correctly in Maya 2020, however, you may need to change some of the materials to aiStandard in order for it to work in Arnold.
